FROM bellsoft/liberica-openjdk-alpine:latest AS BuildProject1
WORKDIR /app
COPY ./java ./src
RUN mkdir ./out
RUN javac -sourcepath ./src -d out ./src/org/core/some/Main.java

FROM scratch AS readyFiles
COPY --from=BuildProject1 /app/out /bin
